[template]
src = "bcm4334x.tmpl"
dest = "/etc/modprobe.d/bcm4334x.conf"
keys = [
     "/factory/device/wifi",
     "/common/device/wifi",
     "/local/device/wifi"
]
format = "ini"
reload_cmd = "/usr/libexec/bcm4334x/bcm4334x.sh"
